cudnn:                                            # [linux64]
  - undefined                                     # [linux64]
cuda_compiler_version:                            # [linux64]
  - None                                          # [linux64]
  