{% set name = "clr_loader" %}
{% set version = "0.2.7.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7a8b3f8fbb1bcbbb6382d887e21d1742d4f10b5ea209e4ad95568fe97e1c7c6

build:
  number: 0
  # We skip for PPC64 and s390x since the dotnet binaries for this architecture aren't available.
  skip: True # [ppc64le or s390x]
  skip: True # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
    - toml
  run:
    - cffi >=1.13
    - python

test:
  requires:
    - pip
    - importlib_resources
  commands:
    - pip check

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  description: |
    Implements a generic interface for loading one of the CLR (.NET) runtime
    implementations and calling simple functions on them.
  dev_url: https://github.com/pythonnet/clr-loader
  doc_url: https://pythonnet.github.io/clr-loader/

extra:
  recipe-maintainers:
    - m-rossi
    - sumit0190
