{% set name = "clr_loader" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82ed5fb654729d14fd88296e74bb6b84eb2cfb976ff4b7d49d4e449fd78a226b

build:
  number: 0
  # We skip for PPC64 since the dotnet binaries for this architecture aren't available.
  skip: True # [ppc64le]
  skip: True # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - cffi >=1.13
    - python

test:
  requires:
    - pip
    - importlib_resources
  commands:
    - pip check

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  description: |
    Implements a generic interface for loading one of the CLR (.NET) runtime
    implementations and calling simple functions on them.
  dev_url: https://github.com/pythonnet/clr-loader
  doc_url: https://pythonnet.github.io/clr-loader/

extra:
  recipe-maintainers:
    - m-rossi
    - sumit0190
