{% set name = "clr_loader" %}
{% set version = "0.2.4" %}
{% set checksum = "7b4516e363b3054b46e93a3d39cb1968e58d6eeccea0e8c0bc86f1100a2f4cc5" %}
{% set build = "0"}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - dotnet-sdk >=6
  host:
    - python >=3.7
    - pip
    - setuptools >=61
    - setuptools-scm
    - wheel
  run:
    - cffi >=1.13
    - python >=3.7

test:
  imports:
    - clr_loader
  requires:
    - pip
    - dotnet-runtime 6.0
    - importlib_resources
    - mono
  commands:
    - pip check

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  dev_url: https://github.com/pythonnet/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
