{% set name = "clr_loader" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e073e9aaf49d1ae2f56ecba27987ad5fb68be4bcd9dd34a5bed8f0e4e128366

build:
  number: 1
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=80
    - setuptools-scm
    - toml
  run:
    - cffi >=1.17
    - python

test:
  requires:
    - pip
    - python
    - dotnet # [not linux]
    - pytest >=9.0,<10
  source_files:
    - tests/
    - example/
  imports:
    - clr_loader
  commands:
    - pip check
    # dotnet 10 unavailable: since example/example.csproj has it's TargetFrameworks specified as "net10.0;netstandard2.0", we
    # must make MSBuild "unsee" net10.0 part (unsupported target), either via patch, or via configuration (is as done here).
    # Otherwise MSBuild behavior is to error out if any of the targets are unsupported. Can be skipped once dotnet 10 is available.
    - echo -p:TargetFrameworks=netstandard2.0> example\Directory.Build.rsp  # [win]
    # Skip mono tests - no package available on main channel
    # Skip linux tests - compatibility issues with dotnet
    # Skip test_coreclr - we don't have dotnet dotnet-sdk version 10 which the tests build against. restore once available.
    # Skip win-arm64 .NET Framework subprocess tests not viable in main channel
    - pytest -v tests/ -k "not mono and not test_coreclr_properties and not test_coreclr" # [not linux and not (win and arm64)]

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  description: |
    Implements a generic interface for loading one of the CLR (.NET)
    runtime implementations and calling simple functions on them.
  dev_url: https://github.com/pythonnet/clr-loader
  doc_url: https://pythonnet.github.io/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
    - sumit0190
