{% set name = "clr_loader" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e073e9aaf49d1ae2f56ecba27987ad5fb68be4bcd9dd34a5bed8f0e4e128366

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=80
    - setuptools-scm
    - toml
  run:
    - cffi >=1.17
    - python

test:
  requires:
    - pip
    - python
    - dotnet # [not linux]
    - pytest >=9.0,<10
  source_files:
    - tests/
    - example/
  imports:
    - clr_loader
  commands:
    - pip check
    # Skip mono tests - no package available on main channel
    # Skip linux tests - compatibility issues with dotnet
    # Skip test_coreclr - we don't have dotnet dotnet-sdk version 10 which the tests build against. restore once available.
    - pytest -v tests/ -k "not mono and not test_coreclr_properties and not test_coreclr" # [not linux]

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  description: |
    Implements a generic interface for loading one of the CLR (.NET)
    runtime implementations and calling simple functions on them.
  dev_url: https://github.com/pythonnet/clr-loader
  doc_url: https://pythonnet.github.io/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
    - sumit0190
