{% set name = "clr_loader" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6af3d582c3de55ce9e9e676d2b3dbf6bc680c4ea8f76c58786739a5bdcf6b52d

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools >=75
    - wheel
    - toml
  run:
    - cffi >=1.17  # [py>=38]
    - python

test:
  requires:
    - pip
    - python
    - dotnet # [not linux]
    - pytest >=7.0
  source_files:
    - tests/
    - example/
  imports:
    - clr_loader
  commands:
    - pip check
    # Skip mono tests - no package available on main channel
    # Skip linux tests - compatibility issues with dotnet
    - pytest -v tests/ -k "not mono and not test_coreclr_properties" # [not linux]

about:
  home: https://github.com/pythonnet/clr-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generic pure Python loader for .NET runtimes
  description: |
    Implements a generic interface for loading one of the CLR (.NET)
    runtime implementations and calling simple functions on them.
  dev_url: https://github.com/pythonnet/clr-loader
  doc_url: https://pythonnet.github.io/clr-loader

extra:
  recipe-maintainers:
    - m-rossi
    - sumit0190
